### ISSUE TITLE
Picked image is rotated 90 degrees on Android

### ISSUE THREAD

**Issue by dzebas** [dimonovdd/Xamarin.MediaGallery#101]
**Description**
When you pick image with PickAsync on Android result image is rotated by 90 degrees.
Same code works fine in iOS.

**Expected behavior**
Picked image should be displayed in same orientation as it was originally taken e.g. portrait or landscape.

**Steps to reproduce the behavior**
```
var request = new MediaPickRequest( 1, MediaFileType.Image )
{
    PresentationSourceBounds = PhotoSize.Full,
    Title = "Select image"
};

var results = await MediaGallery.PickAsync( request );
var file = results?.Files?.ToArray()?.First();

byte[] imageData;
var stream = await file.OpenReadAsync(); 

using (MemoryStream ms = new MemoryStream())
{
    stream.CopyTo( ms );
    imageData = ms.ToArray();
}

return imageData;
```

**Configuration**
Device: Samsung S7, Samsung Galaxy Tab A7
OS Version: Android 11
Plugin Version: 2.1.1
Framework: Xamarin

**Comment by dimonovdd** [comment]
Hi. This is correct behavior. Images are processed without any changes, See metadata

**Comment by dzebas** [comment]
Thank you [dimonovdd](https://github.com/dimonovdd) for a quick reply!

So if I want to display it the way it was originally taken, what should I do? You mentioned metadata, do you have any samples on how to use it?

Cheers.

**Comment by dimonovdd** [comment]
See sample project. 
I use  [MetadataExtractor](https://www.nuget.org/packages/MetadataExtractor/)
