### ISSUE TITLE
GPS metadata of images taken with the CapturePhotoAsync method is set to 0.

### ISSUE THREAD

**Issue by bizyyosh** [dimonovdd/Xamarin.MediaGallery#102]
### Description
Images taken using the CapturePhotoAsync method do not contain GPS information.

The info.plist describes the permissions for using the camera and location information.

I am not familiar with development on iOS.
I don't know if the plugin is the cause.
Any advice would be appreciated.

### Expected behavior
Latitude and longitude of the shooting location are included in the meta data.

### Steps to reproduce the behavior
```
if (!MediaGallery.CheckCapturePhotoSupport())
    return;

var status = await Permissions.RequestAsync<Permissions.Camera>();

if (status != PermissionStatus.Granted)
    return;

using (var file = await MediaGallery.CapturePhotoAsync())
{
    var stream = await file.OpenReadAsync();
    var exif = ExifReader.ReadJpeg(stream);
}
```

### Screenshots or Videos
<img width="429" alt="スクリーンショット 2022-08-15 14 26 06" src="https://user-images.githubusercontent.com/76941241/184581667-cd9ceeed-087c-40d6-bea4-8b0fdc3eb5a9.png">

### Configuration
 - Device:  iPhone 13 mini
 - OS Version: 15.6
 - Plugin Version: 2.1.1
 - Framework: Xamarin.Forms

**Comment by dimonovdd** [comment]
Try use [MetadataExtractor](https://www.nuget.org/packages/MetadataExtractor). It works correctly for me.

![telegram-cloud-photo-size-2-5201955108223565501-y](https://user-images.githubusercontent.com/59065470/204378697-7dfd6197-8d68-43ef-90bc-bc1df02e3c6a.jpg)

**Comment by AceCoderLaura** [comment]
I used MetadataExtractor as well as [exiflibrary](https://github.com/oozcitak/exiflibrary) and neither can read any GPS data on the image returned by CapturePhotoAsync.
I'm using Xamarin.MediaGallery 2.2.1

**Comment by AceCoderLaura** [comment]
For Android I added `await Permissions.RequestAsync<Permissions.LocationWhenInUse>();` before calling CapturePhotoAsync and that fixed it for Android but iOS still doesn't return an image with GPS data.
