### ISSUE TITLE
Bad image rotation 

### ISSUE THREAD

**Issue by draganDBL** [dimonovdd/Xamarin.MediaGallery#105]
First  I take image with  phone camera , image is in good orientation. Then after uploading same image inside the app orientation is not good . Any idea how to fix this .
I'm  testing this on Android 
### Steps to reproduce the behavior
1. 
2. 
3. 

### Configuration
 - Device:  Android 
 - OS Version:  11 
 - Plugin Version: 2.1.1
 - Framework: Xamarin or MAUI : Xamarin Forms

**Comment by dimonovdd** [comment]
Hi, https://github.com/dimonovdd/Xamarin.MediaGallery/issues/101

**Comment by draganDBL** [comment]
Hi @dimonovdd  I'm looking on post you send me but still  can't figure it out .  How to make rotation right way

**Comment by sokrog** [comment]
Hello, I have the same problem and I don't know how to solve it

**Comment by dimonovdd** [comment]
I can't know how you want to rotate the image.

For example: https://stackoverflow.com/questions/49652589/rotate-uiimage-in-xamarin-ios
