### ISSUE TITLE
Initializer is not accessible on Android platform

### ISSUE THREAD

**Issue by requenaxii** [dimonovdd/Xamarin.MediaGallery#107]
### Description
I'm triying to initialize the plugin and is not accessible for Xamarin.Android from MainActivity.

### Screenshots or Videos
<img width="340" alt="Screenshot 2022-11-10 at 17 12 46" src="https://user-images.githubusercontent.com/9119054/201149187-1f0b242e-61f2-44bc-9311-15e2d2e253b2.png">

### Configuration
 - Device: Android
 - OS Version: Any
 - Plugin Version: 2.1.1
 - Framework: Xamarin.Forms 4.8 .NET 6.0.5

**Comment by dimonovdd** [comment]
Are you sure you added the nuget?

**Comment by dimonovdd** [comment]
need more information
