### ISSUE TITLE
MediaPickResult.Files return a wrong selection order on Android

### ISSUE THREAD

**Issue by TT702** [dimonovdd/Xamarin.MediaGallery#120]
### Description

My application will ask user to pick some images and put those images on a canvas while maintaining the order they choose.

Everything work perfectly on iOS, "MediaPickResult.Files" return the images using the order that user select.
But on Android it seems always return images using a different order instead of the order when user make selection.

### Actual Behavior

![MediaPicker](https://user-images.githubusercontent.com/7391602/228858584-421c991d-b721-40aa-b0cc-617da0ecfc5b.png)

When user select images using order such as **[6, 9, 13, 1]** or **[1, 13, 6, 9]** or **[6, 1, 13, 9]**.
MediaPickResult.Files always return images using order **[13, 1, 9, 6]**.

### Expected behavior

Return the images using the same order as user select **[6, 9, 13, 1]** or **[1, 13, 6, 9]** or **[6, 1, 13, 9]**.

### Configuration
 - Device: Android Emulator (Pixel 5 - Android 13 - API 33), 
 - OS Version: Android 13
 - Plugin Version: Latest
 - Framework: MAUI

**Comment by dimonovdd** [comment]
it does not depend on the plugin in any way. I think the photo is sorted by [Photo Picker](https://developer.android.com/training/data-storage/shared/photopicker)

**Comment by TT702** [comment]
I see...
So there is no way that plugin knows the order that user selected?
