### ISSUE TITLE
Support .net standard 2.0

### ISSUE THREAD

**Issue by Brosten** [dimonovdd/Xamarin.MediaGallery#13]
## Summary
Since UWP projects doesn't support .net standard 2.1, it would be great if this library could support ,net standard 2.0. Otherwise all xamarin forms setups including UWP will be out of scope, regardless if this picking functionality is to be used by UWP or not.

**Comment by gaelian** [comment]
@dimonovdd so close to successfully integrating your code, but it looks like I've just hit this issue as well. My app uses the Fabulous F# framework for Xamarin Forms. F# depends on .NETStandard 2.0. :(

**Comment by dimonovdd** [comment]
I will try to change .net standard version today
