### ISSUE TITLE
README Sample Code Improvements

### ISSUE THREAD

**Issue by jfversluis** [dimonovdd/Xamarin.MediaGallery#21]
Just tried the sample code from the README on iOS and if you've not asked permission before it will never ask permission with this snippet

```csharp
var status = await Permissions.CheckStatusAsync<SaveMediaPermission>();

if (status != PermissionStatus.Granted)
    return;

await MediaGallery.SaveAsync(MediaFileType.Video, filePath);
```

The `status` will be Unknown and it will leave the method before actually asking for permission.

Additionally, it might be good to note that if you try to save without a file extension, i.e.: `await MediaGallery.SaveAsync(MediaFileType.Image, "myScreenshot");` there will be an exception.

Great work btw! Making a video on this soon! :)

**Comment by dimonovdd** [comment]
@jfversluis Hi. Thanks.

Unfortunately, my English is not very good.And it's hard enough for me to write documentation, But I will try to fix it soon

**Comment by jfversluis** [comment]
Don't worry about it! I don't mean write a lot of Docs, just update the sample code here: https://github.com/dimonovdd/Xamarin.MediaGallery#saveasync

So that it works OK with the permissions for iOS.

And an extra bullet here: https://github.com/dimonovdd/Xamarin.MediaGallery#ios-1

Something like:
> * Make sure to add a file extension when calling `SaveAsync()`, else it will result in an exception

Let me know if you need any help :)
