### ISSUE TITLE
IMediaFile doesn't include the FullPath

### ISSUE THREAD

**Issue by raulandresduque** [dimonovdd/Xamarin.MediaGallery#36]
### Description
It is not possible to get the path where the file(s) where selected

### Actual Behavior
IMediaFile doesn't include the FullPath

### Expected behavior
Have the FullPath or at least the Path, it makes the plugin unusable sine how are you going to access the file later, you will need the FullPath

### Steps to reproduce the behavior
1. Select a file (PickAsync)
2. Inspect IMediaFile collection returned
3. IMediaFile doesn't contain the path of the file

### Screenshots or Videos
N/A

### Reproduction Link
N/A

### Configuration
 - Device: Any
 - OS Version: Any
 - Plugin Version: 1.0.0

**Comment by dimonovdd** [comment]
@raulandresduque  Hi
It is not possible. Android and iOS have security policies that protect user data, so we can't get the real path to the file.
You can also view the documentation update in Xamarin.Essentials. 
- https://github.com/xamarin/Essentials/pull/1759
- https://github.com/MicrosoftDocs/xamarin-docs/pull/3290
