### ISSUE TITLE
return filepath or name for created video

### ISSUE THREAD

**Issue by Stecpoint** [dimonovdd/Xamarin.MediaGallery#41]
## Summary
here created file with timestamp https://github.com/dimonovdd/Xamarin.MediaGallery/blob/b9a26c94cf3c1065b6f0c8a81cbfd6b12c49b901/MediaGallery/MediaGallery/SaveMedia.android.cs

how we can get this path or name?

**Comment by dimonovdd** [comment]
This is almost unrealistic for a cross-platform implementation. We will have to request additional permissions, etc. Getting the file path is basically not consistent with the concept of iOS and android. 
You can also read this discussion: https://github.com/dimonovdd/Xamarin.MediaGallery/discussions/37
