### ISSUE TITLE
App Crashes when I take 150+ photos using CapturePhotoAsync() in IOS platform .

### ISSUE THREAD

**Issue by thanigaiharan** [dimonovdd/Xamarin.MediaGallery#89]
### Description

we are using this nuget in Xamarin.ios application. Our application is a Fleet management application where we used to do inspection for multiple vehicle tires .  While doing inspection we take multiple photos for tires (around 200 photos for one vehicle). While doing so the app crashes in "await MediaGallery.CapturePhotoAsync()".  we are unable to handle this exception and even the crash log is not reported in Testflight. Due to this crash we are losing the inspection data and user need to do inspection again. Appreciate the help to fix this issue soon.

### Actual Behavior

App Should not crash.

### Expected behavior

App crashes in iPad Pro (120 photos) , Iphone XR (around 300 photos),  iPhone 11 Pro (400 photos)

### Code snippet

```csharp

try
{
    var photo = await MediaGallery.CapturePhotoAsync();

    string photoPath = await SavePhotoLocallyAsync(photo, directory);

    var options = new CompressImageOptions
    {
        CompressionQuality = this.GetCompressionQuality(photoResolution)
    };

    //Android throws a "java.lang.RuntimeException: Canvas: trying to draw too large bitmap" exception when taking pictures on 64MP phones.
    //Added a MaxWidthHeight constraint to control max resolution.
    if (ApplicationHelper.SelectedPlatform == ApplicationHelper.ApplicationPlatform.Android)
    {
        const int SIXTEEN_MEGAPIXEL_WIDTH = 4920;
        options.PhotoSize = PhotoSize.MaxWidthHeight;
        options.MaxWidthHeight = SIXTEEN_MEGAPIXEL_WIDTH;
    }

    await this.compressImageService.ResizeAndCompressImage(photoPath, options);

    photo.Dispose();

    return photoPath;
}
catch(Exception ex)
{
    throw ex;
}
```

### Steps to reproduce the behavior
1. 
2. 
3. 

### Configuration
 - Device:Ipad Pro ,  iPhone XR, Iphone 11 pro, iPhone se (almost all iOS devices we tested).
 - OS Version: 15.0.1, 
 - Plugin Version: xamarin.MediaGallery 2.1.1

**Comment by dimonovdd** [comment]
@thanigaiharan Hi. It seems to me that you are facing memory leaks. Have you tried using Xamarin Profiler or subscribing to `ReceiveMemoryWarning`? 200 photos is quite a lot. On which line does the app crash?

**Comment by thanigaiharan** [comment]
@dimonovdd Thanks for your quick reply.  The app crashes in "var photo = await MediaGallery.CapturePhotoAsync();". If this method call throws exception if there is a memory leak then we can catch and avoid the app crash.

**Comment by thanigaiharan** [comment]
@dimonovdd when we call "await MediaGallery.CapturePhotoAsync()" method it shows the 
![image](https://user-images.githubusercontent.com/7297955/150383118-f28f5e0c-b343-4892-8951-79935c54216c.png)

The app crashes when I click on the Shutter button to take photo. Appreciate your help on this.

**Comment by dimonovdd** [comment]
I do not know how to help, I will not be able to test it. I have iPhone 12 mini and 13 Pro. I will have to take more than 400 pictures every time. 
Could you provide more information? For example, you can collect logs from an iPhone using [Console app on Mac](https://support.apple.com/guide/console/welcome/mac)

**Comment by thanigaiharan** [comment]
@dimonovdd I am getting this error in console log when ever I click on the Shutter button after I call "await MediaGallery.CapturePhotoAsync()".

error	01:57:52.245770+0800	BridgestoneTTMSTouchIOS	findWriterForTypeAndAlternateType:119: unsupported file format 'public.heic'

![image](https://user-images.githubusercontent.com/7297955/150395521-87eeb4a2-1973-40f2-beb4-e2b69e64dd31.png)

**Comment by thanigaiharan** [comment]
@dimonovdd When I checked with the Xamarin Profiler. Below is the screen shots 
1. Initial stage

![image](https://user-images.githubusercontent.com/7297955/150494622-1829e3da-19c8-4860-ae4d-518b7f9fcac4.png)

2. Just before the crash 

![image](https://user-images.githubusercontent.com/7297955/150494869-e45a66a8-903d-4683-ac00-1fc4893adb19.png)

**Comment by dimonovdd** [comment]
@thanigaiharan Can you email me the full logs from native logs from Xcode or Console?

**Comment by dimonovdd** [comment]
1) Have you used Essentials? is there such this issue?
2) Did you also get this crash in debug or in release builds?

**Comment by dimonovdd** [comment]
@thanigaiharan You can find the device logs in Xcode -> Window -> Devices and Simulators -> View Device Logs
I hope that today or tomorrow you will send more information. I would like to try to help you with it tomorrow.

**Comment by thanigaiharan** [comment]
@dimonovdd emailed you the details.

**Comment by thanigaiharan** [comment]
@dimonovdd sent email with the crash logs.

**Comment by dimonovdd** [comment]
200 images is pretty high for normal usage. I thihk that  you should report this issue to [Apple](https://developer.apple.com/bug-reporting/). You can specify that [UIImagePickerController](https://developer.apple.com/documentation/uikit/uiimagepickercontroller) is used to capture photos. 

If you write to apple, please let us know about the progress of solving the problem here

**Comment by thanigaiharan** [comment]
@dimonovdd When we capture the photo and show the preview with 'Use photo' and 'Retake' option (as shown in below screenshot), are we using the UIImageViewer . If so are you setting the new Image(filename) or UIImage.FromFile(filepath)? 

![image](https://user-images.githubusercontent.com/7297955/150865324-36d9d1da-a3d6-4eef-8523-16bec5bb4b17.png)

**Comment by dimonovdd** [comment]
> When we capture the photo and show the preview with 'Use photo' and 'Retake' option (as shown in below screenshot), are we using the UIImageViewer

No this is the native behavior of `UIImagePickerController`. 
All the project sources are in this repository. You can watch it.

1) [PlatformCapturePhotoAsync](https://github.com/dimonovdd/Xamarin.MediaGallery/blob/9c1fff256d2b1344181fff0ed0a188bb6cfe44b6/MediaGallery/MediaGallery/PickMedia.ios.cs#L114)

2) [PhotoFile](https://github.com/dimonovdd/Xamarin.MediaGallery/blob/9c1fff256d2b1344181fff0ed0a188bb6cfe44b6/MediaGallery/MediaFile/MediaFile.ios.cs#L99)

**Comment by dimonovdd** [comment]
I'm wondering if there are any updates on this?
