### ISSUE TITLE
Unable to pick photos from Gallery on iOS simulator

### ISSUE THREAD

**Issue by joeykang** [dimonovdd/Xamarin.MediaGallery#92]
### Description
I'm able to pick photos from Gallery when running on iOS simulator.
### Actual Behavior
OpenReadAsync() throws an exception like below.

_Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.jpeg" UserInfo={NSLocalizedDescription=Cannot load representation of type public.jpeg, NSUnderlyingError=0x600002006a90 {Error Domain=NSCocoaErrorDomain Code=256 "The file “version=1&uuid=B84E8479-475C-4727-A4A4-B77AA9980897&mode=compatible.jpeg” couldn’t be opened." UserInfo={NSURL=file:///Users/joey/Library/Developer/CoreSimulator/Devices/D004FFB9-AEC8-46F5-BDCE-67F4392FF633/data/Containers/Shared/AppGroup/40F09F17-AF44-4239-A0B8-B26FC04C9BD9/File%20Provider%20Storage/photospicker/version=1&uuid=B84E8479-475C-4727-A4A4-B77AA9980897&mode=compatible.jpeg, NSFilePath=/Users/joey/Library/Developer/CoreSimulator/Devices/D004FFB9-AEC8-46F5-BDCE-67F4392FF633/data/Containers/Shared/AppGroup/40F09F17-AF44-4239-A0B8-B26FC04C9BD9/File Provider Storage/photospicker/version=1&uuid=B84E8479-475C-4727-A4A4-B77AA9980897&mode=compatible.jpeg, NSUnderlyingError=0x60000207f8a0 {Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)"}}}}_
### Expected behavior
Stream should be returned with OpenReadAsync()
### Steps to reproduce the behavior
1. await MediaGallery.PickAsync()
2. OpenReadAsync()
3. 

### Configuration
 - Device: iPhone 12 mini simulator
 - OS Version:  iOS 15.2
 - Plugin Version: 2.1.1
 - Framework: Xamarin 5
 - Xcode: 13.2.1

**Comment by dimonovdd** [comment]
https://github.com/dimonovdd/Xamarin.MediaGallery/discussions/56

**Comment by joeykang** [comment]
The suggestion in #56 did not work on my end. Even if I pick a photo downloaded with Safari on simulator it returns the same exception. Wonder if this could be a simulator issue running on M1 Mac.

**Comment by dimonovdd** [comment]
https://stackoverflow.com/questions/67672550/error-domain-nsitemprovidererrordomain-code-1000-cannot-load-representation-of

**Comment by nicjay** [comment]
I know this is closed, but thought it was worth mentioning the Essentials MediaPicker version of OpenReadAsync() does work without issue on the simulator. I don't know yet how the implementations differ, but I also wasn't able to find any workaround to avoid this crash with MediaGallery, even emptying the gallery and downloading fresh images with Safari.

**Comment by dimonovdd** [comment]
@nicjay hi. Sorry, I haven't seen your messages
MediaGallery uses new PHPicker, Essentials uses outdated UIImagePicker.

Do you get the same error as in the description?

**Comment by nicjay** [comment]
@dimonovdd Yes, identical error.

**Comment by dimonovdd** [comment]
You can check in google: this error is really on apple's side

**Comment by eddieyanez** [comment]
I have the same problem on the latest version of Xcode and the iOS simulator. Has anyone found a workaround since then by any chance?

**Comment by dimonovdd** [comment]
@eddieyanez Hi. Apparently apple still hasn't fixed it

https://developer.apple.com/forums/thread/658135

**Comment by eddieyanez** [comment]
> @eddieyanez Hi. Apparently apple still hasn't fixed it
> 
> https://developer.apple.com/forums/thread/658135

That really sucks! Do you happen to know if the outdated UIImagePicker allows multiple image selection?

**Comment by dimonovdd** [comment]
There is a workaround: 

You can save any image from Safari on simulator. The Picker will work good with such images
