### ISSUE TITLE
Get errors with a fresh download in VS 17.1.4 and 17.2.0 Preview 3.0

### ISSUE THREAD

**Issue by WillAutioItrax** [dimonovdd/Xamarin.MediaGallery#98]
### Description
Get errors with a fresh download in VS 17.1.4 and 17.2.0 Preview 3.0 (VS Professional)

I want to see how the Samples run and then determine how our app can use this package. 
Currently, I am only interested in the Xamarin Forms Samples so I did not try Maui.

### Actual Behavior
Out of the box, I opened Xamarin MediaGallery Samples from VS 17.1.4 and from VS 17.2.0.Preview 3.0. I got the following errors

VS 17.1.4
=========
`Samples

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with monoandroid11.0 (MonoAndroid,Version=v11.0). Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.Android	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.Android\Sample.Android.csproj	1	
  
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1	
 
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1
  	
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1	
  
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1
 	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-android	Sample.Common	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Common\Sample.Common.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-android	Sample.Common	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Common\Sample.Common.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-android	Sample.Common	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Common\Sample.Common.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-android	Sample.Maui	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\MAUI\Sample.Maui.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-ios, net6.0-android	Sample.Maui	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\MAUI\Sample.Maui.csproj	1	
`

VS 17.2.0.Preview 3.0
=====================
samples

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with monoandroid11.0 (MonoAndroid,Version=v11.0). Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.Android	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.Android\Sample.Android.csproj	1
  	
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1
  	
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1	
  
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1	
  
Error	NU1202	Package Xamarin.MediaGallery.Permision.Maui 2.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Package Xamarin.MediaGallery.Permision.Maui 2.0.0 supports:
  - net6.0 (.NETCoreApp,Version=v6.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)
  - net6.0-ios15.0 (.NETCoreApp,Version=v6.0)	Sample.iOS	C:\Users\wauti\source\repos5\2204\Xamarin.MediaGallery-main\Sample\Xamarin\Sample.iOS\Sample.iOS.csproj	1	

### Expected behavior
That the app should be able to run without errors in at least one of the versions of VS

### Steps to reproduce the behavior
1. Download a zip
2. extract the code
3. open in VS 17.1.4 or VS 17.2.0.Preview 3.0.
4. see the errors

### Configuration
 - Device: n/a (can't get to a device if I can't get past errors)
 - OS Version: See Device. My PC has Win 11.
 - Plugin Version: Xamarin MediaGallery v 2.1.1
 - Framework: Xamarin or MAUI   Xamarin Forms

**Comment by dimonovdd** [comment]
@WillAutioItrax Hi

Unfortunately I only use Mac. Yes, because of the support of Maui, this Sample is very difficult for the IDE
I was running it from Terminal.

I'll think about it, and maybe I'll make the sample for Forms with a separate solution. But I don't have much time right now. You can make a pull request yourself
