### ISSUE TITLE
[iOS] Image picker returns incorrect onrientation, when image was not taken holding phone "90 deg left"

### ISSUE THREAD

**Issue by rr-rv** [dimonovdd/Xamarin.MediaGallery#99]
### Description
iOS stores images in non rotated and save the rotation compared to the camera in exif data i believe.
When picking with the ImagePicker iOS handles the rotation in the image previews.
This is not taking into consideration when the lib delivers the images picked from gallery.

This seams to be a problem with all multi image pickers for xamarin.forms out there. 
But serval people hinted that this one didn't have it, so here is a bug report.

if I'm using the lib. wrong or this is expected behaviour, then don't hesitate to close this again.
im trying to let a user pick some images and the phone uploads them to a server where they are used later.

### Actual Behavior

After picking images in gallery and gotten the image with *.OpenReadAsync() they show as if they where all taken with the phone held at "90 deg. left"

### Expected behavior

*.OpenReadAsync() returns a image with the expected orientation.

### Steps to reproduce the behavior
take images holding the phone ex. upright or 90 deg right.
use MediaGallery.PickAsync to get them
use OpenReadAsync() to get bytes/stream
display image on screen.

### Screenshots or Videos

![2-edit](https://user-images.githubusercontent.com/26006002/166901693-ec76de26-ff96-47df-87dd-bd7c8533a0f1.jpg)
![3-edit](https://user-images.githubusercontent.com/26006002/166901709-4c2f110e-3148-427d-90e0-cf1894b34b89.jpg)

### Configuration
 - Device: Xs
 - OS Version: 15.1
 - Plugin Version: 2.1.1
 - Framework: Xamarin

**Comment by dimonovdd** [comment]
Hi. Yes, this plugin does not convert images in any way. [But it adds missing data containing orientation information](https://github.com/dimonovdd/Xamarin.MediaGallery/blob/f8e70a7b91de7c45ae4dea55d4f0a2ed14036b64/MediaGallery/MediaFile/MediaFile.ios.cs#L121)

**Comment by rr-rv** [comment]
alright. thats on me. 
so the info is in the stream.
thanks mate for the quick response.
